# DO NOT DELETE

../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximNoC.h ../src_new_gpu/NoximTile.h ../src_new_gpu/NoximRouter.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximMain.h ../src_new_gpu/NoximBuffer.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximStats.h ../src_new_gpu/NoximPower.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximGlobalRoutingTable.h ../src_new_gpu/fc_router.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximLocalRoutingTable.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximReservationTable.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximProcessingElement.h
../src_new_gpu/NoximNoC.o: ../src_new_gpu/NoximGlobalTrafficTable.h
../src_new_gpu/NoximRouter.o: ../src_new_gpu/NoximRouter.h ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximRouter.o: ../src_new_gpu/NoximBuffer.h ../src_new_gpu/NoximStats.h
../src_new_gpu/NoximRouter.o: ../src_new_gpu/NoximPower.h ../src_new_gpu/NoximGlobalRoutingTable.h
../src_new_gpu/NoximRouter.o: ../src_new_gpu/NoximLocalRoutingTable.h
../src_new_gpu/NoximRouter.o: ../src_new_gpu/NoximReservationTable.h
../src_new_gpu/db_node.o: ../src_new_gpu/db_node.h 
../src_new_gpu/fc_router.o: ../src_new_gpu/fc_router.h
../src_new_gpu/NoximProcessingElement.o: ../src_new_gpu/NoximProcessingElement.h
../src_new_gpu/NoximProcessingElement.o: ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximProcessingElement.o: ../src_new_gpu/NoximGlobalTrafficTable.h
../src_new_gpu/NoximBuffer.o: ../src_new_gpu/NoximBuffer.h ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximStats.o: ../src_new_gpu/NoximStats.h ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximStats.o: ../src_new_gpu/NoximPower.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximGlobalStats.h ../src_new_gpu/NoximNoC.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximTile.h ../src_new_gpu/NoximRouter.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximMain.h ../src_new_gpu/NoximBuffer.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximStats.h ../src_new_gpu/NoximPower.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximGlobalRoutingTable.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximLocalRoutingTable.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximReservationTable.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximProcessingElement.h
../src_new_gpu/NoximGlobalStats.o: ../src_new_gpu/NoximGlobalTrafficTable.h
../src_new_gpu/NoximGlobalRoutingTable.o: ../src_new_gpu/NoximGlobalRoutingTable.h
../src_new_gpu/NoximGlobalRoutingTable.o: ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximLocalRoutingTable.o: ../src_new_gpu/NoximLocalRoutingTable.h
../src_new_gpu/NoximLocalRoutingTable.o: ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximLocalRoutingTable.o: ../src_new_gpu/NoximGlobalRoutingTable.h
../src_new_gpu/NoximGlobalTrafficTable.o: ../src_new_gpu/NoximGlobalTrafficTable.h
../src_new_gpu/NoximGlobalTrafficTable.o: ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximReservationTable.o: ../src_new_gpu/NoximReservationTable.h
../src_new_gpu/NoximReservationTable.o: ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximPower.o: ../src_new_gpu/NoximPower.h ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximCmdLineParser.o: ../src_new_gpu/NoximCmdLineParser.h ../src_new_gpu/NoximMain.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximMain.h ../src_new_gpu/NoximNoC.h ../src_new_gpu/NoximTile.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximRouter.h ../src_new_gpu/NoximBuffer.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximStats.h ../src_new_gpu/NoximPower.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximGlobalRoutingTable.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximLocalRoutingTable.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximReservationTable.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximProcessingElement.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximGlobalTrafficTable.h ../src_new_gpu/fc_router.h
../src_new_gpu/NoximMain.o: ../src_new_gpu/NoximGlobalStats.h ../src_new_gpu/NoximCmdLineParser.h
